LOGIN_ENDPOINT = "https://idpdecathlon.oxylane.com/as/authorization.oauth2?client_id=C3502aaaf2ef68e5412c3c82c1406c8316bd9b055&response_type=code&redirect_uri=https://eplanningplus.decathlon.net/login&scope=openid%20profile%20email"
PLANNING_ENDPOINT = "https://eplanning-api.decathlon.net/es/planning/api/v2/planning/monthlyPlanningByCollaborator"
COLLABORATOR_ENDPOINT = "https://eplanning-api.decathlon.net/es/api/v2/collaborators"
SCOPES = ["https://www.googleapis.com/auth/calendar"]

SECTION = {
    "A": "Absentismo",
    "B": "Baja",
    "C": "Complementaria",
    "D": "Comp. Nocturna",
    "E": "Descanso efectivo Año en curso",
    "F": "Festivo",
    "G": "Vacaciones adeudadas",
    "H": "Comp. Festiva",
    "I": "Incapacidad laboral",
    "J": "Abs. justificado no retribuido",
    "K": "Cajas",
    "KC": "Cajas complementaria",
    "KF": "Cajas Festiva",
    "KN": "Cajas Nocturna",
    "M": "Explotación",
    "M1": "Descarga e Implantación",
    "M1F": "Descarga e Implantación Festiva",
    "M1N": "Descargar e Implantación Nocturna",
    "M2": "Formaciones",
    "M2F": "Formación festiva",
    "M3": "Management",
    "M3F": "Management Festiva",
    "M3N": "Management Nocturna",
    "M4": "Probadores",
    "M4F": "Probadores Festiva",
    "M5": "Permanencias",
    "M5F": "Permanencia Festiva",
    "M5N": "Permanencia Nocturna",
    "M6": "Wellcomer y Goodbyer",
    "M6F": "Wellcomer y Goodbyer Festivo",
    "M7": "Mudanzas",
    "M7F": "Mudanza Festiva",
    "M7N": "Mudanza Nocturna",
    "MF": "Explotación Festiva",
    "MN": "Explotación Nocturna",
    "N": "Nocturna",
    "O": "Online",
    "P": "Permiso Retribuido Convenio",
    "Q": "Falta puntualidad",
    "R": "Reparación/Taller",
    "RC": "Reparación/Taller Complementaria",
    "RCF": "Reparación/Taller Complementaria Festiva",
    "RF": "Reparación/Taller Festiva",
    "S": "Circularidad",
    "SC": "Circularidad Complementaria",
    "SCF": "Circularidad Complementaria Festiva",
    "SF": "Circularidad Festiva",
    "V": "Vacaciones",
    "W": "Vacaciones por complementarias",
    "X": "Normal",
    "Z1": "Accidente de trabajo CON BAJA",
    "Z2": "Accidente de trabajo SIN BAJA"
}